openapi: 3.0.3
info:
  title: Pulse API
  description: AI Empowered Insights
  version: 0.2.0
servers:
  - description: Pulse Host
    url: https://localhost:8080/
tags:
  - name: Summary
    description: Handles pulse summary requests
paths:
  /summary/github/users/{username}:
    get:
      tags:
        - Summary
      description: Get Pulse summary for Github user
      operationId: getGithubUserSummary
      parameters:
        - in: path
          name: username
          description: The username to target the summary for
          required: true
          schema:
            type: string
          example: "jesse0michael"
        - description: organization
          in: query
          name: organization
          required: false
          schema:
            type: string
          example: "Jesse0Michael"
        - description: repository
          in: query
          name: repository
          required: false
          schema:
            type: string
          example: "pulse"
        - description: startDate
          in: query
          name: start date
          required: false
          schema:
            type: string
            format: date-time
          example: "2023-08-13T00:00:00Z"
        - description: endDate
          in: query
          name: end date
          required: false
          schema:
            type: string
            format: date-time
          example: "2023-08-20T00:00:00Z"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/summary"
          description: the Pulse summary
components:
  schemas:
    summary:
      type: object
      required:
        - summary
      properties:
        summary:
          description: The AI generated summary that corresponds to the provided parameters
          type: string
      example:
        summary: "You had a great week"
